//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.componens
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pen
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ColorId { get; set; }
        public Nullable<int> ViewId { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Type Type { get; set; }
        public virtual View View { get; set; }
    }
}
